### Numpy Indexing and Selection
### In this lecture we will discuss how to select elements or groups of elements from an array.

In [2]:
import numpy as np


In [3]:
# Creating sample array
arr = np.arange(0, 11)


In [4]:
# Show
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing and Selection
### The simplest way to pick one or some elements of an array looks very similar to python lists:

In [5]:
# Get a value at an index
arr[8]


8

In [6]:
# Get values in a range
arr[1:5]


array([1, 2, 3, 4])

### Broadcasting
### Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [11]:
#Setting a value with index range (Broadcasting)
arr[0:6]=100

#Show
arr

# Reset array
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:

#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice

#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [14]:
#Now note the changes also occur in our original array!
# => Thay ddoior car gias trij cua mang ban dau

arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Data is not copied, it's a view of the original array! This avoids memory problems!

In [15]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing a 2D array (matrices)
### The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [19]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [21]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [23]:
# Getting individual element value
arr_2d[1, 1]

25

In [34]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,:3]
# arr_2d

array([[ 5, 10, 15],
       [20, 25, 30]])

In [35]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

### Fancy Indexing
### Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [37]:
#Set up matrix
arr2d = np.zeros((10,10))

In [38]:
#Length of array
arr_length = arr2d.shape[1]

In [39]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [41]:
#Fancy indexing allows the following

arr2d[[0 , 1, 2, 3]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [42]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

### Selection
### Let's briefly go over how to use brackets for selection based off of comparison operators.

In [53]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
arr > 3 # from index 3 is true, else 0 => 2 false


array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [48]:
bool_arr = arr>4

In [49]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [50]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])